# Generated by Django 3.0.3 on 2020-10-10 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enqtypename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=15)),
                ('emailid', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceno', models.CharField(max_length=15)),
                ('vehiclename', models.CharField(max_length=100)),
                ('vehiclemodel', models.CharField(max_length=30)),
                ('vehiclebrand', models.CharField(max_length=50)),
                ('vehicleregno', models.CharField(max_length=15)),
                ('servicedate', models.DateField()),
                ('servicetime', models.TimeField()),
                ('deltype', models.CharField(max_length=50)),
                ('pickupaddr', models.CharField(max_length=300)),
                ('servicereqdate', models.DateField()),
                ('servicecharge', models.CharField(max_length=50)),
                ('partscharge', models.CharField(max_length=50)),
                ('othercharge', models.CharField(max_length=50)),
                ('adminremark', models.CharField(max_length=500)),
                ('adminstatus', models.CharField(max_length=100)),
                ('adminremarkdate', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Category')),
                ('serviceby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Mechanic')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enqno', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=500)),
                ('enqdate', models.DateField()),
                ('adminresponse', models.CharField(max_length=500)),
                ('adminstatus', models.CharField(max_length=50)),
                ('adminremarkdate', models.DateField()),
                ('enqtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.EnquiryType')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
