# Generated by Django 3.0.3 on 2020-10-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='adminremarkdate',
            field=models.DateField(null=True),
        ),
    ]
