# Generated by Django 3.0.3 on 2020-10-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20201016_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='adminremark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='adminremarkdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='adminstatus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='othercharge',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='partscharge',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='serviceby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.Mechanic'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='servicecharge',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='servicereqdate',
            field=models.DateField(null=True),
        ),
    ]
